apiVersion: 1
prune: true

datasources:
  - name: Yamcs Demo
    uid: yamcs-demo
    type: jaops-yamcs-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      hosts:
        demo-host:
          name: Local Yamcs
          description: Yamcs service from this Docker Compose stack
          path: yamcs:8090
          tlsEnabled: false
          tlsInsecure: false
          authEnabled: false
          username: admin
          protobuf: true
      endpoints:
        demo_realtime:
          name: Demo realtime
          description: Realtime processor for the drone demo
          host: demo-host
          instance: demo
          processor: realtime
        demo_replay:
          name: Demo replay
          description: Replay processor for the drone demo
          host: demo-host
          instance: demo
          processor: replay
    secureJsonData:
      demo-host-password: admin
